### ISSUE TITLE
Custom chat name coloring, or coloring based on experience/role?

### ISSUE THREAD

**Issue by luxaritas** [eternagame/HTML-Chat#14]
Custom name coloring is something which is rather fun, and I hesitate to remove it, if not explicitly allow everyone to do so. However, the concept of colors based on experience or role has been around for quite a while, and seems to have good support (and I personally like the idea): https://getsatisfaction.com/eternagame/topics/colorize_players_names_in_chat_regarding_their_experience

Could also be up for debate as to whether we even want to make a differentiation like this, but I know it is done elsewhere, in Eyewire as an example. This could also create a readability reduction with many people posting in the same color, which is why many IRC clients have automatic colors assigned (granted, that can already more or less happen with the existing mechanism from the Flash chat, as many users can have very similar shades, which does happen pretty often). Again though, other implementations get away from it (Foldit it just straight white). Definitely open for discussion.

**Comment by hoglahoo** [comment]
As long as we don't have a bunch of rainbow text all the time I don't care :)  Some kind of differentiation between new users and older users might be nice for when support/help questions come up in chat. Doesn't necessarily have to be color, could be like a couple of people have done on occasion and put a symbol (such as a star) next to their nick

**Comment by rhiju** [comment]
:thumbsup: for special symbols for experienced users (which would be earned). maybe a star for experts in puzzle solving & a test-tube for folks willing to dispense advice on labs.

**Comment by luxaritas** [comment]
I'm all for the symbols idea, and it would allow custom name colors. Closing this and creating new separate issues for those.
