### ISSUE TITLE
Report user

### ISSUE THREAD

**Issue by luxaritas** [eternagame/HTML-Chat#15]
Brought up quite early on: https://getsatisfaction.com/eternagame/topics/ability_to_report_inappropriate_chat

Also has been discussed in topics made in response to spam popping up. I'd imagine this should ping a mod (via Eterna PM, IRC PM, popup box, etc - needs to be determined) and (possibly) send an email to someone for possible additional action/record keeping (would need to figure out where to send it). Ideally the offending chat history can somehow be tied back to the log (could eventually tie into a new chatbot, make use of IRCv3 history and message tagging where a user could even select the specific messages, etc).

**Comment by hoglahoo** [comment]
agreed

**Comment by luxaritas** [comment]
Resolved in 400bc48e
