### ISSUE TITLE
Handle disconnects/errors

### ISSUE THREAD

**Issue by luxaritas** [eternagame/HTML-Chat#3]
While this probably shouldn't happen, it would be good to provision for (automatically reconnecting, or at least notifying the user/allowing for a reconnect to be manually triggered).

**Comment by guyguy2001** [comment]
#48 solves _most_ of it, but when I plug my internet cable out it doesn't catch the error, I will need to check if it connects again when I plug it back , but when I made my pc go into sleep mode and come back the new system works fine.

**Comment by luxaritas** [comment]
Resolved via #48
