### ISSUE TITLE
Make automatic links smarter

### ISSUE THREAD

**Issue by luxaritas** [eternagame/HTML-Chat#30]
For example, URLs surrounded in parenthesis should not have the closing paren included in the link. This is probably the most common issue that would be run into, but should probably look into other possibilities. Should probably also not make a link for URLs that are not preceded by a space (except for any exclusions like parenthesis), so that something like awww... does not get turned into a link.

**Comment by luxaritas** [comment]
Commas after a URL should probably also not be included.

**Comment by luxaritas** [comment]
Period after URL as well. Note that these things need to be contextualized, that is characters (comma/period) must be the last character after a link, not included in it, as they could be valid URL characters, a closing paren should have an opening paren before the link, or at least have no opening paren within the link, etc.

**Comment by Omei** [comment]
Good idea to make it smart enough to take into account common punctuation before and after an intended URL  But spending a lot of effort trying to take into account all the legal, but improbable, URL possibilities is probably a rabbit hole best left unentered.

**Comment by luxaritas** [comment]
Resolved as of 01b363ac0a78cedd9e934
