### ISSUE TITLE
No blank messages of just spaces

### ISSUE THREAD

**Issue by luxaritas** [eternagame/HTML-Chat#35]
Should probably be calling strip() on the textarea content when a user hits enter before checking if it's blank. Quick fix.

**Comment by DanielOaks** [comment]
Not sure whether users post any sort of ascii art or similar, maybe `rstrip` (or the relevant js function) instead if you're keeping+sending the stripped version out?

**Comment by luxaritas** [comment]
That's a fair point, though the multiple sizes the client is presented in makes ASCII art not extremely viable (~250px wide in the sidebar of the site, ~1kpx wide on the dedicated chat page, and who knows what resolution on mobile devices once [the app](https://github.com/EteRNAgame/eternachat) is rewritten with Cordova and this repo is used for it - and once the site becomes more mobile-friendly), and I haven't seen anyone doing such either in the time I've been around. At any rate, my primary issue is completely blank text, so the strip doesn't even need to be included in the sent message, only for [the check if the textarea is empty](https://github.com/EteRNAgame/HTML-Chat/blob/dbd32f86aa2b63c4df9821f868b4fa9aa387fa4f/js/chat.js#L350).

**Comment by DanielOaks** [comment]
Nice, looks cool then

**Comment by luxaritas** [comment]
Resolved in 658e9fd9001d65687752ea9476cffcb62afbe027
