### ISSUE TITLE
mcustomscrollbar breaks chat inside cross-domain iframe

### ISSUE THREAD

**Issue by luxaritas** [eternagame/HTML-Chat#52]
We planned for www.eternagame.org to (temporarily) load the chat from irc.eternagame.org as an iframe. A bug in the custom scrollbar causes an error when this happens.

There is a patch for this at https://github.com/malihu/malihu-custom-scrollbar-plugin/pull/451, but apparently, the repo is not maintained. Should we fork it and merge in the fix (@omei, I think this would be up to you)? Or should we use a different library? This will be replaced once the rewrite happens anyhow (assuming we use Vue, we should ditch jQuery as a dependency).

**Comment by luxaritas** [comment]
Two examples:
https://github.com/noraesae/perfect-scrollbar
https://github.com/idiotWu/smooth-scrollbar

**Comment by guyguy2001** [comment]
May I patch any of them in? If so, are there any preferences to which?

**Comment by luxaritas** [comment]
@guyguy2001 Preferences to which what?

**Comment by guyguy2001** [comment]
Which library to use

**Comment by luxaritas** [comment]
Frankly, what I care about is that it works and it looks ok. :)

**Comment by luxaritas** [comment]
Resolved in 3201bac
